<a href="https://colab.research.google.com/github/Rivu-21/MLStudyJams2023_GDSC_TIU/blob/main/ML_StudyJams2023_Day_1_Numpy%26Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 1 of Study Jams

In [1]:
!python --version

Python 3.9.16


In [7]:
import numpy as np
import pandas as pd
import random

In [3]:
data = np.array([1, 2, 3])

In [4]:
data.max()

3

In [5]:
dataones = np.ones((3, 3))

In [6]:
dataones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
datazeros = np.zeros((3, 5))

In [9]:
datazeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
datarandom = np.random.random(3)

In [11]:
datarandom

array([0.35761361, 0.70414673, 0.72377043])

In [21]:
a = np.array([1, 2, 3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])

<class 'numpy.ndarray'>
(3,)
1 2 3


In [13]:
a[0] = 5
print(a)

[5 2 3]


In [14]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [15]:
print(b.shape, type(b), b[0, 1])

(2, 3) <class 'numpy.ndarray'> 2


In [19]:
c = np.full((5, 2), 7)
c

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [26]:
d = np.eye(3, dtype='int64')
d

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [27]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
row_r1 = a[1, :]
row_r2 = a[1:2, :]

In [28]:
row_r1, row_r2

(array([5, 6, 7, 8]), array([[5, 6, 7, 8]]))

In [29]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
bool_idx = (a>3)

In [32]:
bool_idx

array([[False, False],
       [False,  True],
       [ True,  True]])

In [33]:
print(a[bool_idx])

[4 5 6]


In [35]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
np.add(x, y), np.subtract(x, y), np.multiply(x, y), np.divide(x, y), np.sqrt(x)

(array([[ 6,  8],
        [10, 12]]),
 array([[-4, -4],
        [-4, -4]]),
 array([[ 5, 12],
        [21, 32]]),
 array([[0.2       , 0.33333333],
        [0.42857143, 0.5       ]]),
 array([[1.        , 1.41421356],
        [1.73205081, 2.        ]]))

In [36]:
np.dot(x, y)

array([[19, 22],
       [43, 50]])

In [38]:
x.T

array([[1, 3],
       [2, 4]])

(weights.transpose*matrix)+bias

In [ ]:
np.add(np.multiply(w.T, X), b)

In [40]:
import pandas as pd
df = pd.read_csv('/content/music.csv')
df

Artist  Genre   Listeners     Plays
0  Billie Holiday   Jazz     1300000  27000000
1    Jimi Hendrix   Rock     2700000  70000000
2     Miles Davis   Jazz     1500000  48000000
3             SIA    Pop     2000000  74000000

In [41]:
df['Artist']

0    Billie Holiday
1      Jimi Hendrix
2       Miles Davis
3               SIA
Name: Artist, dtype: object

In [42]:
df[1:4]

Artist  Genre   Listeners     Plays
1  Jimi Hendrix   Rock     2700000  70000000
2   Miles Davis   Jazz     1500000  48000000
3           SIA    Pop     2000000  74000000

In [44]:
df.loc[1:3, ['Artist']]

Artist
1  Jimi Hendrix
2   Miles Davis
3           SIA

In [46]:
df[df[' Genre'] == ' Jazz']

Artist  Genre   Listeners     Plays
0  Billie Holiday   Jazz     1300000  27000000
2     Miles Davis   Jazz     1500000  48000000

In [47]:
df[df[' Listeners'] > 1800000]

Artist  Genre   Listeners     Plays
1  Jimi Hendrix   Rock     2700000  70000000
3           SIA    Pop     2000000  74000000

In [48]:
df.groupby(' Genre').sum()

Listeners     Plays
 Genre                      
 Jazz      2800000  75000000
 Pop       2000000  74000000
 Rock      2700000  70000000

In [57]:
df['Avg Plays'] = df[' Plays'] / df[' Listeners']
df

Artist  Genre   Listeners     Plays  Avg Plays
0  Billie Holiday   Jazz     1300000  27000000  20.769231
1    Jimi Hendrix   Rock     2700000  70000000  25.925926
2     Miles Davis   Jazz     1500000  48000000  32.000000
3             SIA    Pop     2000000  74000000  37.000000